In [5]:
# Import Libraries

import numpy as np
import networkx as nx
from scipy.spatial.distance import cosine

In [6]:
# Create Vectors

np.random.seed(42)

vectors = np.random.rand(5, 4)

print(vectors)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]


In [7]:
# Create HNSW Graph

graph = nx.Graph()

for i in range(len(vectors)):
    graph.add_node(i)

print(graph.nodes)

[0, 1, 2, 3, 4]


In [9]:
# Add Connections

for i in range(len(vectors)):
    for j in range(i + 1, len(vectors)):

        # Use 1 - cosine distance to get cosine similarity
        similarity = 1 - cosine(
            vectors[i],
            vectors[j]
        )

        if similarity > 0.7:
            graph.add_edge(
                i,
                j,
                weight=similarity
            )

In [10]:
# Query Vector

query = np.random.rand(4)

print("Query:", query)

Query: [0.61185289 0.13949386 0.29214465 0.36636184]


In [13]:
# Calculate Similarities

similarities = []

for i in range(len(vectors)):

    # Use 1 - cosine distance to get cosine similarity
    score = 1 - cosine(
        query,
        vectors[i]
    )

    similarities.append((i, score))

In [12]:
# Rank Results

similarities.sort(
    key=lambda x: x[1],
    reverse=True
)

print(similarities)

[]


In [14]:
# Top Results

top_results = similarities[:3]

print("Top Results:")
print(top_results)

Top Results:
[(0, np.float64(0.7290519730227715)), (1, np.float64(0.6436353587864527)), (2, np.float64(0.7870768391421533))]


In [15]:
# Results

print("Number of Vectors:", len(vectors))
print("Number of Connections:", graph.number_of_edges())
print("Top Similar Vectors:", top_results)

Number of Vectors: 5
Number of Connections: 4
Top Similar Vectors: [(0, np.float64(0.7290519730227715)), (1, np.float64(0.6436353587864527)), (2, np.float64(0.7870768391421533))]
