In [1]:
# Import NumPy

import numpy as np

In [2]:
# Input Data

batch_size = 2
num_heads = 2
seq_len = 4
head_dim = 3

np.random.seed(42)

Q = np.random.randn(batch_size, num_heads, seq_len, head_dim)
K = np.random.randn(batch_size, num_heads, seq_len, head_dim)
V = np.random.randn(batch_size, num_heads, seq_len, head_dim)

In [4]:
# Calculate Attention Scores

scores = np.matmul(Q, K.transpose(0, 1, 3, 2))

In [5]:
# Scaling

scores = scores / np.sqrt(head_dim)

In [6]:
# Causal Mask

mask = np.triu(np.ones((seq_len, seq_len)), k=1)

scores = np.where(mask == 1, -1e9, scores)

In [7]:
# Softmax

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scores)

In [8]:
# Attention Output

attention_output = np.matmul(attention_weights, V)

print(attention_output)

[[[[ 0.29612028  0.26105527  0.00511346]
   [ 0.13457712 -0.2492356  -0.12448416]
   [-0.27215641 -0.74451735 -0.16454509]
   [ 0.01521444 -0.16033292 -0.10535628]]

  [[ 0.25755039 -0.07444592 -1.91877122]
   [ 0.1087155  -0.00388263  0.37717572]
   [-0.01159186  0.07697395  1.49278207]
   [ 0.03695045  0.10195461 -0.93801539]]]


 [[[ 0.79103195 -0.90938745  1.40279431]
   [-0.47273283 -0.04709742  1.85672579]
   [ 0.47792861 -0.71141836  1.48036741]
   [ 0.47065447 -0.9202303   1.22423652]]

  [[-1.06230371  0.47359243 -0.91942423]
   [ 0.29442207 -0.17917922 -0.6091702 ]
   [ 0.63912995 -0.79113909 -0.13096623]
   [ 0.0450401  -0.22884287 -0.54251881]]]]


In [9]:
# Results

print("Q Shape:", Q.shape)
print("K Shape:", K.shape)
print("V Shape:", V.shape)
print("Output Shape:", attention_output.shape)

Q Shape: (2, 2, 4, 3)
K Shape: (2, 2, 4, 3)
V Shape: (2, 2, 4, 3)
Output Shape: (2, 2, 4, 3)
